name: gg
channels:
  - conda-forge
  - bioconda
  - main
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bcftools=1.16
  - binutils_impl_linux-64=2.39
  - binutils_linux-64=2.39
  - boost=1.76.0
  - boost-cpp=1.76.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - ccache=4.3
  - certifi=2022.12.7
  - cmake=3.19.6
  - curl=7.87.0
  - expat=2.4.1
  - gcc=12.2.0
  - gcc_impl_linux-64=12.2.0
  - gcc_linux-64=12.2.0
  - gsl=2.7
  - gxx=12.2.0
  - gxx_impl_linux-64=12.2.0
  - gxx_linux-64=12.2.0
  - htslib=1.16
  - icu=68.2
  - jellyfish=2.2.10
  - jemalloc=4.5.0
  - jsoncpp=1.9.5
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - krb5=1.20.1
  - ld_impl_linux-64=2.39
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.87.0
  - libdeflate=1.13
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.4.2
  - libgcc=7.2.0
  - libgcc-devel_linux-64=12.2.0
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libgomp=12.2.0
  - liblapack=3.9.0
  - libnghttp2=1.51.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libsanitizer=12.2.0
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-devel_linux-64=12.2.0
  - libstdcxx-ng=12.2.0
  - libuuid=2.32.1
  - libuv=1.40.0
  - libzlib=1.2.13
  - lz4-c=1.9.3
  - ncurses=6.3
  - numpy=1.22.3
  - openssl=1.1.1t
  - perl=5.32.1
  - pip=21.2.4
  - pkg-config=0.29.2
  - pkgconfig=1.5.4
  - python=3.9.15
  - python_abi=3.9
  - readline=8.1.2
  - rhash=1.4.3
  - setuptools=58.0.4
  - sqlite=3.36.0
  - sysroot_linux-64=2.12
  - tk=8.6.12
  - tzdata=2021e
  - wheel=0.37.0
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.4.9
