INPUT_DIR: "/mnt/gs21/scratch/mansourt/pangenome/"
TEMP_FOLDER: "/mnt/gs21/scratch/mansourt/"
INPUT_REFERENCE: "/mnt/gs21/scratch/mansourt/pangenome/GRCh38_full_analysis_set_plus_decoy_hla.fa"
INPUT_INDEX: "tmp_index"
BEAGLE: "/home/mshokrof/genotyping-experiments/SV_genotyping/beagle.22Jul22.46e.jar"
BEAGLE_MAP: "/home/mshokrof/genotyping-experiments/SV_genotyping/plink.autsomal.map"
OUTPUT_DIR: "/mnt/gs21/scratch/mansourt/pangenome/pangenome_GG_GRCh38/"
GG_BUILD_PATH: "/mnt/gs21/scratch/mansourt/TheGreatGenotyper/build2/"


