configfile: "config.yaml"

# Get list of input files
with open(config['input_file'], 'r') as f:
    INPUT_FILES = [line.strip() for line in f]

# Define rule all as a point of entry
rule all:
    input:
        expand("{prefix}.sig", prefix=[i[:-9] for i in INPUT_FILES])

# Rule to run sourmash
rule run_sourmash:
    input:
        "{prefix}.fasta.gz"
    output:
        "{prefix}.sig"
    conda:
         "env.yaml"
    threads: 1
    priority: 1
    resources:
        mem_mb=5000,
        cores=1,
	parallel_kmc=1,
	nodes = 1,
        time = lambda wildcards,attempt: attempt * 60 * 1,
        partition =  ""		
    log: "{prefix}.sourmash.log"
    shell:
        "gunzip -c {input} | sourmash sketch dna -p k=31,k=51,scaled=1000,noabund - -o {output}"
